# Generated by Django 5.2.1 on 2026-03-23 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('description', models.CharField()),
                ('date', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.category')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.user')),
            ],
        ),
    ]
