# Generated by Django 5.2.1 on 2026-03-28 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('monthly_limit', models.BigIntegerField()),
                ('month', models.CharField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('total_expense', models.BigIntegerField()),
                ('month', models.CharField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.user')),
            ],
        ),
    ]
