# Generated by Django 5.2.1 on 2026-04-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0003_alter_budget_bid_alter_category_cid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
